apiVersion: v1
kind: Service
metadata:
  name: nginx-external-service
spec:
  type: ClusterIP
  externalIPs:
    - 10.178.0.10
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
  selector:
    app: nginx-app
