apiVersion: batch/v1
kind: Job
metadata:
  name: tools-job
spec:
#  completions: 5
  parallelism: 3
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: tools-container
          image: amsy810/tools:v2.0
          command: ["sleep"]
          args: ["15"]
      restartPolicy: Never
